### ISSUE TITLE
broken: Stacktraces aren't connected to projects?

### ISSUE THREAD

**Issue by LeoUfimtsev** [ericwill/build_test_script#12]
Hey ya, 

For stack traces, project name printed doesn't appear to be actual project name.

Example is today's stack trace:

`org.eclipse.ui.workbench.texteditor.tests      # <<<< this should be SWT's test project.
java.lang.AssertionError: Test timed out. TitleListener not fired
        at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_browser_Browser.validateTitleChanged(Test_org_eclipse_swt_browser_Browser.java:802)
        at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_browser_Browser.test_setUrl_local(Test_org_eclipse_swt_browser_Browser.java:768)
        at org.eclipse.test.EclipseTestRunner.run(EclipseTestRunner.java:749)
        at org.eclipse.test.EclipseTestRunner.run(EclipseTestRunner.java:350)
`

**Comment by LeoUfimtsev** [comment]
ping
